### ISSUE TITLE
Variable value with space results in LineParse error

### ISSUE THREAD

**Issue by Boscop** [slapresta/rust-dotenv#63]
I have this in my `.env` file:
```
MONITOR=SD300_S24D300H (HDMI)
```
But when I use the latest version of dotenv, I get:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Error(LineParse("SD300_S24D300H (HDMI)"), State { next_error: None, backtrace: Some(stack backtrace:
   0:     0x7ff65d8e286d - backtrace::backtrace::trace<closure>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\backtrace-0.3.0\src\backtrace\mod.rs:42
   1:     0x7ff65d8d8d6b - backtrace::capture::Backtrace::new
                        at D:\projects\VaporFlow\target\debug\build\backtrace-17
fa5380aeaf9437\out\capture.rs:79
   2:     0x7ff65d8d526a - error_chain::make_backtrace
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\error-chain-0.10.0\src\lib.rs:417
   3:     0x7ff65d8d5362 - error_chain::{{impl}}::default
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\error-chain-0.10.0\src\lib.rs:504
   4:     0x7ff65d8c30fe - dotenv::Error::from_kind
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:22
   5:     0x7ff65d8c335f - dotenv::{{impl}}::from
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:22
   6:     0x7ff65d8bf34f - core::convert::{{impl}}::into<dotenv::ErrorKind,doten
v::Error>
                        at C:\projects\rust\src\libcore\convert.rs:281
   7:     0x7ff65d8c029d - dotenv::parse_value
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:87
   8:     0x7ff65d8c113b - dotenv::parse_line::{{closure}}
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:168
   9:     0x7ff65d8bb623 - core::option::Option<regex::re_unicode::Captures>::ma
p_or<regex::re_unicode::Captures,core::result::Result<core::option::Option<(coll
ections::string::String, collections::string::String)>, dotenv::Error>,closure>
                        at C:\projects\rust\src\libcore\option.rs:413
  10:     0x7ff65d8c0c4d - dotenv::parse_line
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:161
  11:     0x7ff65d8c1b2b - dotenv::from_file
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:190
  12:     0x7ff65d8bc98e - core::ops::FnOnce::call_once<fn(std::fs::File) -> cor
e::result::Result<(), dotenv::Error>,(std::fs::File)>
                        at C:\projects\rust\src\libcore\ops.rs:2606
  13:     0x7ff65d8bc650 - core::result::Result<std::fs::File, std::io::error::E
rror>::map<std::fs::File,std::io::error::Error,core::result::Result<(), dotenv::
Error>,fn(std::fs::File) -> core::result::Result<(), dotenv::Error>>
                        at C:\projects\rust\src\libcore\result.rs:457
  14:     0x7ff65d8c27fe - dotenv::from_path
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:228
  15:     0x7ff65d8c2c60 - dotenv::from_filename
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:251
  16:     0x7ff65d8c306e - dotenv::dotenv
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db
9ec823\dotenv-0.10.0\src\lib.rs:268
```

Before I updated to the latest version of dotenv it was working..

EDIT: It doesn't even work with values without spaces like `D:\projects\foo`, I still get a LineParse error. Those values used to work before too.

**Comment by daboross** [comment]
I believe this is an intentional change to more closely match the interpretation of shells like bash, in which `A=B C` means "execute command C with A=B as the environment".

To use a value with a space, you need to surround the value with `"` quotes now. Like:

```
MONITOR="SD300_S24D300H (HDMI)"
```

**Comment by Boscop** [comment]
It works with 0.8, the above output was version 0.10, and with 0.9 I get `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parsing{ line: "SD300_S24D300H (HDMI)" }', src\libcore\result.rs:859`

If I'd put quotation marks around, then I'd run into this issue:
https://github.com/slapresta/rust-dotenv/issues/49

And why do paths without spaces also fail?

**Comment by daboross** [comment]
hmm, #49 should have been fixed by the same change which disallowed `A=B C` without quotes. Let me test this locally

**Comment by daboross** [comment]
`MONITOR="SD300_S24D300H (HDMI)"` works completely correctly for me with `dotenv` 0.10 @Boscop.

It is true that this behavior changed, and is backwards incompatible with older versions:

dotenv 0.10 will parse `MONITOR="SD300_S24D300H (HDMI)"` as `SD300_S24D300H (HDMI)`, and will fail for `MONITOR=SD300_S24D300H (HDMI)`.

dotenv <0.9 will parse `MONITOR="SD300_S24D300H (HDMI)"` as `"SD300_S24D300H (HDMI)"` and `MONITOR=SD300_S24D300H (HDMI)` as `SD300_S24D300H (HDMI)`.

**Comment by Boscop** [comment]
Ok, but it still crashes on paths with no spaces but backslashes, no matter if I put them in quotes or not, why?

**Comment by Boscop** [comment]
Ah nevermind, it works with single quotes or double backslashes...

**Comment by daboross** [comment]
Ah, that should still work with quotes and backslashes though... Seems like a separate issue from the spaces though, want to open another issue about it?

**Comment by Boscop** [comment]
I opened another issue: https://github.com/slapresta/rust-dotenv/issues/64
(Btw, if I do `echo "foo\bar"` in linux, it prints `foo\bar`. Not sure how it interprets backslash when sourcing env vars.)

**Comment by alicemaz** [comment]
in short: all sorts of ways. it is worth noting echo is a builtin and behaves differently across shells. but in general single quotes can be relied on to get you the characters you give it, while escapes in double quotes depend entirely on what's doing the interpreting and when
```alice@venus:~ % echo "foo\bar"
foar
alice@venus:~ % echo "foo\\bar"
foo\bar
alice@venus:~ % bash
alice@venus ~ $ echo "foo\bar"
foo\bar
alice@venus ~ $ echo -e "foo\bar"
foar
alice@venus ~ $ echo -e "foo\\bar"
foar
alice@venus ~ $ echo -e "foo\\\bar"
foo\bar
alice@venus ~ $ echo -e 'foo\bar'
foar
alice@venus ~ $ echo -e 'foo\\bar'
foo\bar
alice@venus ~ $ export asdf="foo\bar"
alice@venus ~ $ echo $asdf
foo\bar
alice@venus ~ $ env | grep asdf
asdf=foo\bar
alice@venus ~ $ export asdf="foo\\bar"
alice@venus ~ $ echo $asdf
foo\bar
alice@venus ~ $ env | grep asdf
asdf=foo\bar```
